import { CheckCircle2, CircleDot, Radio, Router, Send, Signal, Wifi } from 'lucide-react';
import { useDemo } from '@/context/DemoContext';
import { getScenarioLoRaStatus, getScenarioNodes } from '@/data/mockData';
import { ConsolePage } from '@/components/layout/ConsolePage';
import { MetricTile } from '@/components/MetricTile';

export function LoRa() {
  const { scenario, isDemo } = useDemo();
  const active = isDemo ? scenario : 'normal';
  const status = getScenarioLoRaStatus(active);
  const nodes = getScenarioNodes(active);
  const transmitted = active === 'joint' || active === 'load' ? '1,249' : '1,248';
  const packetState = active === 'joint' || active === 'load' ? 'PACKET TRANSMITTED' : status.state;
  return <ConsolePage eyebrow="NETWORK / RADIO FABRIC" title="LoRa Network" subtitle="Trace low-power communication from sensor nodes through the gateway to the monitoring dashboard.">
    <div className="flex items-center justify-between border border-cyan-300/20 bg-cyan-300/[0.04] px-4 py-3"><div className="flex items-center gap-3"><Radio size={17} className="text-cyan-300" /><div><div className="text-[11px] font-semibold text-cyan-100">DEMO DATA / RADIO FABRIC</div><div className="mono mt-1 text-[9px] text-slate-500">SIMULATED PACKETS · 433 MHZ CHANNEL</div></div></div><span className={`mono text-[10px] ${packetState === 'PACKET TRANSMITTED' ? 'text-amber-300' : status.state === 'CONNECTED' ? 'text-emerald-300' : 'text-amber-300'}`}>{packetState}</span></div>
    <section className="panel overflow-hidden p-5 md:p-7"><div className="mb-7 text-[11px] font-semibold tracking-[0.16em] text-slate-100">COMMUNICATION PATH</div><div className="grid items-center gap-3 md:grid-cols-[1fr_auto_1fr_auto_1fr_auto_1fr]"><div className="border border-emerald-300/25 bg-emerald-300/[0.05] p-4 text-center"><CircleDot className="mx-auto text-emerald-300" size={20} /><div className="mt-3 text-[10px] font-semibold text-slate-200">SENSOR NODE</div><div className="mono mt-1 text-[10px] text-cyan-200">GB-01-N01</div><div className="mt-2 text-[9px] text-emerald-300">ONLINE</div></div><div className="packet-line relative hidden h-px bg-slate-700 md:block"><span className="packet absolute -top-1 h-2 w-2 rounded-full bg-cyan-300" /></div><div className="border border-cyan-300/25 bg-cyan-300/[0.05] p-4 text-center"><Signal className="mx-auto text-cyan-300" size={20} /><div className="mt-3 text-[10px] font-semibold text-slate-200">LORA</div><div className="mono mt-1 text-[10px] text-cyan-200">433 MHZ</div><div className="mt-2 text-[9px] text-cyan-300">{status.state}</div></div><div className="packet-line relative hidden h-px bg-slate-700 md:block"><span className="packet absolute -top-1 h-2 w-2 rounded-full bg-cyan-300" /></div><div className="border border-emerald-300/25 bg-emerald-300/[0.05] p-4 text-center"><Router className="mx-auto text-emerald-300" size={20} /><div className="mt-3 text-[10px] font-semibold text-slate-200">GATEWAY</div><div className="mono mt-1 text-[10px] text-cyan-200">GB-GW-01</div><div className="mt-2 text-[9px] text-emerald-300">ONLINE</div></div><div className="packet-line relative hidden h-px bg-slate-700 md:block"><span className="packet absolute -top-1 h-2 w-2 rounded-full bg-cyan-300" /></div><div className="border border-cyan-300/25 bg-cyan-300/[0.05] p-4 text-center"><Wifi className="mx-auto text-cyan-300" size={20} /><div className="mt-3 text-[10px] font-semibold text-slate-200">MONITORING</div><div className="mono mt-1 text-[10px] text-cyan-200">DASHBOARD</div><div className="mt-2 text-[9px] text-cyan-300">RECEIVING</div></div></div><div className="mt-6 flex items-center justify-center gap-2 text-[10px] text-slate-500"><Send size={13} className="text-cyan-300" />PACKET ROUTE ACTIVE · <span className={packetState === 'PACKET TRANSMITTED' ? 'text-amber-200' : ''}>{packetState}</span> · LAST PACKET 2 SEC AGO</div></section>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><MetricTile label="NODES ONLINE" value={`${status.nodes}/${status.totalNodes}`} detail="CONNECTED" tone="green" icon={<CheckCircle2 size={15} />} /><MetricTile label="PACKETS SENT" value={transmitted} detail="LAST 15 MIN" icon={<Send size={15} />} /><MetricTile label="PACKETS RECEIVED" value="1,239" detail="99.28% DELIVERY" tone="green" icon={<Wifi size={15} />} /><MetricTile label="PACKET LOSS" value="0.72%" detail="WITHIN LIMIT" tone={active === 'load' ? 'amber' : 'green'} icon={<Signal size={15} />} /></div>
    <div className="grid gap-5 lg:grid-cols-[1fr_.8fr]"><section className="panel p-5"><div className="flex items-center justify-between"><div><div className="text-[11px] font-semibold tracking-[0.16em] text-slate-100">NODE RADIO TABLE</div><div className="mono mt-1 text-[9px] text-slate-500">DEMO DATA · CURRENT FIELD WINDOW</div></div><Radio size={16} className="text-cyan-300" /></div><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[520px] text-left"><thead><tr className="border-b border-slate-700/70 mono text-[9px] text-slate-500"><th className="pb-3">NODE</th><th className="pb-3">STATE</th><th className="pb-3">RSSI</th><th className="pb-3">BATTERY</th><th className="pb-3">LAST PACKET</th></tr></thead><tbody>{nodes.map((node) => { const radioRssi = active === 'normal' ? (node.id.endsWith('01') ? -72 : -75) : node.rssi; const battery = active === 'normal' ? (node.id.endsWith('01') ? 87 : 81) : node.battery; return <tr key={node.id} className="border-b border-slate-700/40 text-[10px]"><td className="py-3 mono text-cyan-200">{node.id}</td><td className={`py-3 ${node.status === 'online' ? 'text-emerald-300' : node.status === 'warning' ? 'text-amber-300' : 'text-rose-300'}`}>{node.status === 'online' ? 'ONLINE' : node.status === 'warning' ? 'WARNING' : 'OFFLINE'}</td><td className="py-3 mono text-slate-300">{radioRssi} dBm</td><td className="py-3 mono text-slate-300">{battery}%</td><td className="py-3 mono text-slate-500">{node.id.endsWith('01') ? '2 sec ago' : '3 sec ago'}</td></tr>; })}</tbody></table></div></section><section className="panel p-5"><div className="text-[11px] font-semibold tracking-[0.16em] text-slate-100">RADIO HEALTH</div><div className="mt-5 space-y-4">{[['RSSI', `${status.rssi} dBm`, status.rssi < -80 ? 52 : 72], ['LINK QUALITY', active === 'load' ? '68%' : '87%', active === 'load' ? 68 : 87], ['GATEWAY', 'CONNECTED', 100]].map(([label, value, width]) => <div key={label as string}><div className="flex justify-between text-[10px]"><span className="text-slate-400">{label as string}</span><span className="mono text-slate-200">{value as string}</span></div><div className="mt-2 h-1.5 bg-slate-800"><div className="h-full bg-cyan-300" style={{ width: `${width}%` }} /></div></div>)}</div><div className="mt-6 border-t border-slate-700/60 pt-4 mono text-[9px] text-slate-500">LATENCY 184 ms · CHANNEL 11 · SPREADING FACTOR 7</div></section></div>
  </ConsolePage>;
}