import { BrainCircuit, Cpu, Gauge, Radio, ScanLine, Waves } from 'lucide-react';
import { useDemo } from '@/context/DemoContext';
import { getScenarioStats, getTinyMlResult } from '@/data/mockData';
import { ConsolePage } from '@/components/layout/ConsolePage';
import { MetricTile } from '@/components/MetricTile';

export function TinyML() {
  const { scenario, isDemo } = useDemo();
  const active = isDemo ? scenario : 'normal';
  const stats = getScenarioStats(active);
  const result = getTinyMlResult(active);
  const scoreColor = result.risk === 'CRITICAL' ? 'bg-rose-300' : result.risk === 'WARNING' ? 'bg-amber-300' : 'bg-emerald-300';
  const timeline = active === 'normal' ? [['21:49:02', 'NORMAL', '0.08'], ['21:50:36', 'NORMAL', '0.07'], ['21:52:14', 'NORMAL', '0.08']] : active === 'vibration' ? [['21:49:02', 'NORMAL', '0.11'], ['21:50:36', 'WARNING', '0.42'], ['21:52:14', 'ANOMALY DETECTED', '0.55']] : active === 'joint' ? [['21:49:02', 'NORMAL', '0.16'], ['21:50:36', 'WARNING', '0.61'], ['21:52:14', 'ANOMALY DETECTED', '0.73']] : [['21:49:02', 'WARNING', '0.54'], ['21:50:36', 'CRITICAL ANOMALY', '0.82'], ['21:52:14', 'CRITICAL ANOMALY', '0.88']];
  return <ConsolePage eyebrow="ANALYTICS / EDGE INFERENCE" title="TinyML Analysis" subtitle="Translate vibration features into an explainable anomaly score and risk classification at the edge.">
    <div className="grid gap-5 xl:grid-cols-[1.2fr_.8fr]">
      <section className="panel panel-accent p-5 md:p-6"><div className="flex items-start justify-between"><div><div className="flex items-center gap-2 text-[11px] font-semibold tracking-[0.16em] text-slate-100"><BrainCircuit size={16} className="text-cyan-300" />ANOMALY SCORE</div><div className="mono mt-1 text-[9px] text-slate-500">GB-01-N01 · WINDOW 256 SAMPLES · SIMULATED</div></div><div className={`border px-2 py-1 text-[9px] font-semibold tracking-[0.12em] ${result.risk === 'CRITICAL' ? 'border-rose-300/30 bg-rose-300/10 text-rose-200' : result.risk === 'WARNING' ? 'border-amber-300/30 bg-amber-300/10 text-amber-200' : 'border-emerald-300/30 bg-emerald-300/10 text-emerald-200'}`}>{result.risk} RISK</div></div><div className="mt-8 flex items-end gap-4"><div className="mono text-6xl font-semibold tracking-tight text-slate-100">{result.anomalyScore.toFixed(2)}</div><div className="pb-2 text-[11px] text-slate-500">/ 1.00<br />CURRENT SCORE</div></div><div className="relative mt-8 h-3 bg-slate-800"><div className="absolute inset-y-0 left-0 w-[40%] bg-emerald-300/30" /><div className="absolute inset-y-0 left-[40%] w-[30%] bg-amber-300/30" /><div className="absolute inset-y-0 right-0 w-[30%] bg-rose-300/30" /><div className={`absolute top-1/2 h-6 w-1.5 -translate-x-1/2 -translate-y-1/2 ${scoreColor} shadow-[0_0_12px_rgba(93,224,237,.35)]`} style={{ left: `${result.anomalyScore * 100}%` }} /></div><div className="mt-2 flex justify-between mono text-[8px] text-slate-500"><span>0.00</span><span>0.40</span><span>0.70</span><span>1.00</span></div><div className="mt-6 grid gap-2 sm:grid-cols-3"><div className="flex items-center gap-2 text-[9px] text-emerald-300"><span className="h-2 w-2 bg-emerald-300" />NORMAL · .00–.39</div><div className="flex items-center gap-2 text-[9px] text-amber-300"><span className="h-2 w-2 bg-amber-300" />WARNING · .40–.69</div><div className="flex items-center gap-2 text-[9px] text-rose-300"><span className="h-2 w-2 bg-rose-300" />CRITICAL · .70–1.00</div></div></section>
      <section className="panel p-5"><div className="text-[11px] font-semibold tracking-[0.16em] text-slate-100">CURRENT CLASSIFICATION</div><div className={`mt-5 border p-4 ${result.risk === 'CRITICAL' ? 'border-rose-300/30 bg-rose-300/[0.06]' : result.risk === 'WARNING' ? 'border-amber-300/30 bg-amber-300/[0.06]' : 'border-emerald-300/30 bg-emerald-300/[0.06]'}`}><div className="mono text-[10px] text-slate-500">TINYML OUTPUT</div><div className="mt-2 text-xl font-semibold text-slate-100">{result.status}</div><div className="mt-2 text-[11px] leading-relaxed text-slate-500">Edge inference compares the current feature window with the healthy bridge baseline.</div></div><div className="mt-5 flex items-center gap-3 border-t border-slate-700/60 pt-4"><Gauge size={17} className="text-cyan-300" /><div><div className="text-[11px] text-slate-200">Model confidence</div><div className="mono mt-1 text-[9px] text-slate-500">{active === 'normal' ? '97.8%' : '93.4%'} · DEMO INFERENCE</div></div></div></section>
    </div>
    <div className="grid gap-5 xl:grid-cols-[1fr_.9fr]"><section className="panel p-5"><div className="flex items-center justify-between"><div className="text-[11px] font-semibold tracking-[0.16em] text-slate-100">FEATURE EXTRACTION</div><ScanLine size={16} className="text-cyan-300" /></div><div className="mt-4 grid grid-cols-2 gap-3"><MetricTile label="RMS" value={stats.rms} detail="ACCELERATION" icon={<Waves size={14} />} /><MetricTile label="PEAK-TO-PEAK" value={stats.peak} detail="ACCELERATION" /><MetricTile label="FFT PEAK" value={stats.fft} detail="FREQUENCY" /><MetricTile label="TILT DEVIATION" value={stats.tilt} detail="ORIENTATION" /></div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[430px] text-left"><thead><tr className="border-b border-slate-700/70 mono text-[9px] text-slate-500"><th className="pb-3">FEATURE</th><th className="pb-3">CURRENT</th><th className="pb-3">HEALTHY BASELINE</th><th className="pb-3">UNIT</th></tr></thead><tbody>{[['RMS', stats.rms.replace(' g', ''), '0.28', 'g'], ['Peak-to-Peak', stats.peak.replace(' g', ''), '0.65', 'g'], ['FFT Peak', stats.fft.replace(' Hz', ''), '13.8', 'Hz'], ['Tilt', stats.tilt.replace('°', ''), '0.6', 'degrees']].map(([label, current, baseline, unit]) => <tr key={label} className="border-b border-slate-700/40 text-[10px]"><td className="py-3 text-slate-300">{label}</td><td className="py-3 mono text-cyan-200">{current}</td><td className="py-3 mono text-slate-400">{baseline}</td><td className="py-3 mono text-slate-500">{unit}</td></tr>)}</tbody></table></div></section><section className="panel p-5"><div className="text-[11px] font-semibold tracking-[0.16em] text-slate-100">ANOMALY TIMELINE</div><div className="mt-5 space-y-0">{timeline.map(([time, status, score], index) => <div key={time} className="relative flex gap-4 pb-5 last:pb-0"><div className="relative flex w-3 justify-center"><span className={`z-10 mt-1.5 h-2.5 w-2.5 rounded-full ${status === 'NORMAL' ? 'bg-emerald-300' : status === 'WARNING' ? 'bg-amber-300' : 'bg-rose-300'}`} />{index < timeline.length - 1 && <span className="absolute top-4 h-full w-px bg-slate-700" />}</div><div className="flex-1 border-b border-slate-700/50 pb-4 last:border-0"><div className="flex justify-between"><span className="text-[11px] text-slate-200">{status}</span><span className="mono text-[9px] text-slate-500">{time} UTC</span></div><div className="mono mt-1 text-[9px] text-slate-500">ANOMALY SCORE <span className="text-cyan-200">{score}</span></div></div></div>)}</div></section></div>
    <section className="panel p-5"><div className="mb-5 text-[11px] font-semibold tracking-[0.16em] text-slate-100">EDGE INFERENCE PIPELINE</div><div className="grid gap-2 md:grid-cols-5">{[['MPU6050', Waves], ['Feature Extraction', ScanLine], ['TinyML Inference', Cpu], ['Anomaly Score', Gauge], ['Risk Classification', Radio]].map(([label, Icon], index) => <div key={label as string} className="relative flex items-center gap-3 border border-slate-700/70 bg-slate-950/15 p-3"><span className="mono text-[9px] text-cyan-300">0{index + 1}</span><Icon size={15} className="text-cyan-300" /><span className="text-[10px] text-slate-300">{label as string}</span>{index < 4 && <span className="absolute -right-2 z-10 hidden text-slate-600 md:block">›</span>}</div>)}</div></section>
  </ConsolePage>;
}